### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by sodiumchl** [openzfs/openzfs-docs#98]
zfs does not compile on the following platform. It was working with zfs 0.83. Help appreciated.

CentOS 7.8, zfs 0.86
```
yum install http://download.zfsonlinux.org/epel/zfs-release.el7_9.noarch.rpm
yum install  zfs

```
```
CC [M]  /var/lib/dkms/zfs/0.8.6/build/module/zfs/qat.o
/var/lib/dkms/zfs/0.8.6/build/module/zfs/zpl_file.c: In function ‘zpl_aio_read’:
/var/lib/dkms/zfs/0.8.6/build/module/zfs/zpl_file.c:344:2: error: implicit declaration of function ‘generic_segment_checks’ [-Werror=implicit-function-declaration]
  ret = generic_segment_checks(iovp, &nr_segs, &count, VERIFY_WRITE);
  ^
/var/lib/dkms/zfs/0.8.6/build/module/zfs/zpl_file.c: At top level:
/var/lib/dkms/zfs/0.8.6/build/module/zfs/zpl_file.c:530:2: error: #error "Unknown direct IO interface"
 #error "Unknown direct IO interface"
  ^
/var/lib/dkms/zfs/0.8.6/build/module/zfs/zpl_file.c:1026:15: error: ‘zpl_direct_IO’ undeclared here (not in a function)
  .direct_IO = zpl_direct_IO,
               ^
  CC [M]  /var/lib/dkms/zfs/0.8.6/build/module/zfs/qat_compress.o
cc1: some warnings being treated as errors
make[5]: *** [/var/lib/dkms/zfs/0.8.6/build/module/zfs/zpl_file.o] Error

```

**Comment by behlendorf** [comment]
It looks like you may be running the Virtuozzo 7 kernel which isn't quite the same as the stock CentOS 7 kernel.  There is a patch for this in openzfs/zfs#11411 but it has not yet been backported to the 0.8 branch.
